

IF OBJECT_ID('ImpLiv_Saidas') Is Not Null 
Drop Table ImpLiv_Saidas
IF OBJECT_ID('ImpLiv_SaiProd') Is Not Null 
Drop Table ImpLiv_SaiProd

----- APAGA LINHAS EM BRANCO
DELETE  NFCE WHERE CNF IS NULL
 
--ALTER TABLE NFCE ALTER COLUMN CNPJ VARCHAR(30)
ALTER TABLE NFCE ALTER COLUMN NCM  int
ALTER TABLE NFCE ALTER COLUMN MOD  VARCHAR(02)
ALTER TABLE NFCE ALTER COLUMN CPROD  DECIMAL(15)
ALTER TABLE NFCE ALTER COLUMN NCM  DECIMAL(15)

alter table NFCE add PICMS VARCHAR(02)
GO

--UPDATE NFCE set cProd = substring(cast(cast(cprod as decimal(15)) as char(20)),1,6)

UPDATE NFCE 
    set cProd=
	  Case When Len(cProd) < 6 Then REPLICATE('0', 6 - LEN(cProd)) +   RTrim(cProd)
		   Else substring(cast(cast(cprod as decimal(15)) as char(20)),1,6) End
     ,CNPJ = SUBSTRING(CNPJ,1,2)+'.'+SUBSTRING(CNPJ,3,3)+'.'+SUBSTRING(CNPJ,6,3)+'/'+SUBSTRING(CNPJ,9,4)+'-'+SUBSTRING(CNPJ,13,2)


----- INSERE NOVOS PRODUTOS 
SELECT DISTINCT CPROD,XPROD,NCM,UCOM from NFCE c
where not exists (select 'y' from produtos y where y.codigo = REPLICATE('0', 6 - LEN(cProd)) +   RTrim(cProd))
  

INSERT INTO PRODUTOS (CODIGO,UNIDADE,COD_CLASSFISC,EMPRESA,GRUPO_FISCAL,Id_Liv_ProdutosOrigem,DESCRICAO,SIT_TRIB)
SELECT 
REPLICATE('0', 6 - LEN(CPROD)) + RTrim(CPROD)  AS CODIGO,
'UN' AS UNIDADE,
SUBSTRING(cast(NCM As varchar(15)),1,4)+'.'+SUBSTRING(cast(NCM As varchar(15)),5,2)+'.'+SUBSTRING(cast(NCM As varchar(15)),7,2) AS COD_CLASSFISC,
'01' AS EMPRESA,
'2',
'1',
SUBSTRING(XPROD,1,50) AS DESCRICAO,
'0' AS SIT_TRIB
FROM NFCE c
where CPROD IS NOT NULL AND
 not exists (select 'y' from produtos y where y.codigo = REPLICATE('0', 6 - LEN(cProd)) +   RTrim(cProd))

-----INSERE PRODUTOS FISCAIS

INSERT INTO PRODUTOS_COD_CONCAT_EFD(EMPRESA, COD_PRODUTO, CODIGO_CONCATENADO, Tipo_Item, Descricao, Unidade, ClassFisc, Genero, ID_LIV_PRODUTOSORIGEM)
select DISTINCT d.Empresa, D.CODIGO, D.CODIGO, g.Tipo_Item,D.Descricao, D.unidade, D.COD_ClassFisc, SUBSTRING(D.COD_ClassFisc,1,2), D.Id_Liv_ProdutosOrigem

from PRODUTOS D
    inner join Fig_GrupoFiscal g on (g.Codigo = D.Grupo_Fiscal)
where  Not exists (select 'x' from Produtos_Cod_Concat_EFD x where D.Empresa=x.Empresa and D.CODIGO = x.CODIGO_CONCATENADO) 
--UPDATE PRODUTOS SET Cod_ClassFisc ='7117.19.00 '
--WHERE Cod_ClassFisc='7.11719e+007   '

 


UPDATE NFCE SET CNPJ = '17.131.911/0002-31'

 UPDATE NFCE SET  VPIS = '0', VCOFINS = '0', VICMS = '0', PICMS = '0', VBC = '0'
 FROM NFCE C
 INNER JOIN EMPRESAS E
 ON E.CGC_EMPRESAS = C.CNPJ
 WHERE Regime_Trib  IN ( '1') 

 UPDATE NFCE SET  VPIS = ROUND(VBC*'0.0065',2), VCOFINS = ROUND(VBC*'0.03',2)
 FROM NFCE C
 INNER JOIN EMPRESAS E
 ON E.CGC_EMPRESAS = C.CNPJ
 WHERE Regime_Trib NOT IN ( '1') AND VBC > 0


SELECT DISTINCT 
CODIGO_EMPRESAS As Empresa,
REPLICATE('0', 6 - LEN(CNF)) + RTrim(CNF) AS DOCUMENTO,
SERIE  AS SERIE,
REPLICATE('0', 6 - LEN(NNF)) + RTrim(NNF) AS COO,
'0001' AS MAQUINA,
'1' AS COD_SIT,
CASE WHEN ESTADO_EMPRESAS = 'SP' THEN '111.111.111-11'
     WHEN ESTADO_EMPRESAS = 'PE' THEN '222.222.222-22'
	 WHEN ESTADO_EMPRESAS = 'RJ' THEN '333.333.333-33'
	 WHEN ESTADO_EMPRESAS = 'MG' THEN '444.444.444-44'
	 WHEN ESTADO_EMPRESAS = 'DF' THEN '555.555.555-55'
	 WHEN ESTADO_EMPRESAS = 'PR' THEN '666.666.666-66'
	 WHEN ESTADO_EMPRESAS NOT IN ('SP', 'PE', 'RJ', 'MG', 'DF', 'PR') THEN ''
	 END CPF_CNPJ,
	 'CONSUMIDOR FINAL'+' '+ESTADO_EMPRESAS AS nome_adquirente,
	 'N' AS CANCELADO,
	 COD_LIV_SPED_MODELO_DCTO AS COD_MOD,
	 serie AS NR_SAT,
	 SUBSTRING(ID,4,47) AS CHAVE_CFE,
	 SUBSTRING([DHEMI],1,10) AS DATA_CUPOM,
	 '' AS CHAVE_CFE_CANCELAMENTO,
	 '' AS DATA_CUPOM_CANCELAMENTO
Into ImpLiv_Saidas
FROM NFCE C
INNER JOIN EMPRESAS E
ON CGC_EMPRESAS = CNPJ
inner join liv_sped_modelo_dcto s
on s.codigo_modelo = c.mod 
WHERE E.Codigo_Empresas NOT IN ('02')



SELECT 
DISTINCT 
CODIGO_EMPRESAS As Empresa,
REPLICATE('0', 6 - LEN(CNF)) + RTrim(CNF) AS Documento,
SERIE  AS SERIE,
REPLICATE('0', 6 - LEN(Nnf)) + RTrim(Nnf) AS COO,
NITEM,
REPLICATE('0', 6 - LEN(CPROD)) + RTrim(CPROD) AS CODIGO_PRODUTO,
P.DESCRICAO,
QCOM AS QTDE,
P.UNIDADE,
Vprod -ISNULL(VDESC,0) AS VR_TOTAL_ITEM,
CASE WHEN VICMS = '0' THEN '090'
     WHEN VICMS > 0 THEN '000' 
	 END ST_ICMS,
CFOP,
isnull(vbc,0)   as VR_BC_ICMS,
ISNULL(VICMS,0) AS VR_ICMS,
ISNULL(PICMS,0) AS ALIQ_ICMS,
'0' AS VR_BC_ICMS_ST,
'0' AS VR_ICMS_ST,
ISNULL(VPIS,0) AS VR_PIS,
ISNULL(VCOFINS,0)AS VR_COFINS,
'0' AS VR_INR,
'0' AS VR_DSF,
Vprod -ISNULL(VDESC,0) AS VR_CONTABIL,
ISNULL(VDESC,0) AS VR_DESCONTO,
'0'  AS VR_DESCONTO_RATEIO,
VUNtrib AS VR_UNITARIO,
CASE WHEN PICMS = 0 THEN 'F1'
     WHEN PICMS = '18' THEN '03T1800'
	 WHEN PICMS = '12' THEN '02T1200'
	 WHEN PICMS = '7' THEN '01T0700'
	 END TOTALIZADOR_SPED,
'0' AS VR_ACRESCIMO_RATEIO,
ISNULL(VBC,0) AS BC_PIS,
case when vpis = '0' then '0'
     when vpis > '0' then '0.065'
end PORC_PIS,
case when vpis = '0' then '99'
     when vpis > '0' then '01'
end ST_PIS,
ISNULL(VBC,0) AS BC_COFINS,
case when vCOFINS = '0' then '0'
     when vCOFINS > '0' then '3.00'
end PORC_COFINS,
case when vpis = '0' then '99'
     when vpis > '0' then '01'
end ST_COFINS,
P.CODIGO AS COD_EAN_GTIN,
P.CODIGO AS CODIGO_PRODUTO_CONCAT,
'0'CANCELADO,
'0' PORC_REDUCAOICMS
Into ImpLiv_SaiProd
FROM NFCE C
INNER JOIN PRODUTOS P
ON P.CODIGO = REPLICATE('0', 6 - LEN(CPROD)) + RTrim(CPROD)
INNER JOIN EMPRESAS E
ON E.CGC_Empresas = C.CNPJ
WHERE E.Codigo_Empresas NOT IN ('02') 
